/**
 * Created by v-jiangz on 8/12/2014.
 */

var errCode = {
    UNKNOWN: 0,
    SUCCESS: 1,

    USER_NAME_NOT_FOUND: 2,
    USER_PASSWORD_INCORRECT: 3,
    USER_LOGIN_SUCCSS: 4,

    USER_REGISTER_FAIL: 5,
    USER_NAME_ALREADY_EXIST: 6,
    USER_REGISTER_SUCCESS: 7,

    NEED_LOGIN: 8,
    USER_LOGOUT_SUCCESS: 9,

    POST_SUCCESS: 10,
    POST_FAIL: 11,
    POST_NOT_EXIST: 12,
    POST_NOT_ALLOW_COMMENT: 13,
    POST_DELETE_FAIL: 14,
    POST_DELETE_SUCCESS: 15
};

module.exports = errCode;